apiVersion: v1
kind: Service
metadata:
  name: argocd-lab-demo-service
  namespace: argocd-lab
spec:
  selector:
    app: argocd-lab-demo-deployment
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
