apiVersion: apps/v1
kind: Deployment
metadata:
  name:  argocd-lab-demo-deployment
  namespace: argocd-lab
  labels:
    app:  argocd-lab-demo-deployment
spec:
  selector:
    matchLabels:
      app: spring-web-demo
  replicas: 1
  template:
    metadata:
      labels:
        app:  spring-web-demo
    spec:
      containers:
      - name:  spring-web-demo
        image:  saga1987/argocd-lab-demo:v1
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort:  80
      restartPolicy: Always
